spring.application.name=tienda

server.port=80

# sem2_Lec2

# formato despliegue de horas y minutos
logging.pattern.dateformat=hh:mm
# para eliminar mensajes invasivos del Spring
spring.main.banner-mode=off
#en desarrollo el "cache"del servidor (false), en produccion "true"
spring.thymeleaf.cache=false
